MEAT-Inc/Fulcrum

FulcrumInjector/AppSettings.json, FulcrumInjector/FulcrumViewContent/ViewModels/InjectorOptionViewModels/FulcrumSessionReportingViewModel.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
=> PR to fix Auth token issues

FulcrumInjector/AppSettings.json, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumConstants.cs, FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumNetworkAnalysisViewModel.cs, FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumPeerToPeerViewModel.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml.cs, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumNetworkAnalysisStyles.xaml, FulcrumInjector/InjectorMainWindow.xaml, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Merging newest UI Changes into develop
=> Built views for network analysis and P2P

FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumNetworkAnalysisViewModel.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Including code changes for tracking Message generation into develop
=> Merge UI Generation for PT Messages

FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/fulcrum_loader.cpp, FulcrumShim/res/fulcrum_shim.rc
Fixed issue with logs not being generated
=> Log generation fix

FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumNetworkAnalysisViewModel.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Built new logic to process argument objects on the network analysis view
=> PR to include new logic for argument generation

FulcrumInjector/FulcrumViewContent/Models/PassThruModels/PassThruExecutionAction.cs, FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumNetworkAnalysisViewModel.cs
All arg parsing done for all command arg types other than the 0500 descriptor object types
=> Include changes for all final arg parsing

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumConstants.cs, FulcrumInjector/FulcrumViewContent/Models/PassThruModels/PassThruExecutionAction.cs, FulcrumInjector/FulcrumViewContent/ViewModels/InjectorCoreViewModels/FulcrumNetworkAnalysisViewModel.cs, FulcrumInjector/FulcrumViewContent/Views/FulcrumDllInjectionTestView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/FulcrumInstalledOeAppsView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/FulcrumPipeStatusView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/FulcrumTitleView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/FulcrumVehicleConnectionInfoView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumDllOutputLogView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumHamburgerCoreView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumInstalledHardwareView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumLogReviewView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumNetworkAnalysisView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumPeerToPeerView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorOptionViews/FulcrumDebugLoggingView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorOptionViews/FulcrumSessionReportingView.xaml.cs, FulcrumInjector/FulcrumViewContent/Views/InjectorOptionViews/FulcrumSettingsPaneView.xaml.cs, FulcrumInjector/InjectorMainWindow.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInstaller/FulcrumInstaller.wixproj, FulcrumShim.sln, FulcrumShim/FulcrumShim.vcxproj, FulcrumShim/res/fulcrum_shim.rc
Finished descriptor routines for command parsing and generation
=> Merge final changes to argument parse and content routines

FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInstaller/FulcrumShim.wxs, FulcrumShim/res/fulcrum_shim.rc, README.md
Built small change for the installer project to handle new SharpWrapper DLL
=> PR For Installer Updates

FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Changed around the routine for expressions generation for a massive speed and reliability improvement. Now ready to release this new version for field testing. Hoping this reduces time needed for in field generation routines
=> PR to merge newly tested and built Expressions Generation code 

FulcrumInjector/FulcrumLogic/FulcrumPipes/FulcrumPipeReader.cs
Merging changes for logging state values for pipe states in the injector log files. Merging into FULC-111
=> PR to merge pipe state logging issue into the feature branch

FulcrumInjector/FulcrumLogic/FulcrumPipes/FulcrumPipeReader.cs
Fixed one more small logging issue that was constantly logging our pipe state values out even when we didn't want them
=> Fixed another small issue with the injector logging

FulcrumInjector/FulcrumLogic/PassThruLogic/PassThruExpressions/ExpressionsGenerator.cs, FulcrumInjector/FulcrumLogic/PassThruLogic/PassThruSimulation/SimulationGenerator.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc, FulcrumTests/FulcrumTestHelpers.cs, FulcrumTests/FulcrumTests.csproj, FulcrumTests/FulcrumTests/FulcrumExpressionsTests.cs, FulcrumTests/FulcrumTests/FulcrumSimulationsTests.cs, FulcrumTests/FulcrumTests/FulcrumTestHelpers.cs
Generator unit test classes are now complete. Merging into feature branch before merging back into main again
=> Merging unit test classes for Expressions and Simulation Generator into Feature Branch

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorOptionViewModels/FulcrumDebugLoggingViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorOptionViews/FulcrumDebugLoggingView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorOptionViews/FulcrumDebugLoggingView.xaml.cs
Added new buttons to open the currently loaded log file externally, or to open it up in a new standalone window instance (not yet built)
=> Small PR to include two new buttons of the debug logging view

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/FulcrumSingletonContent.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/FulcrumViewModelBase.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumLogReviewViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumLogReviewView.xaml.cs, FulcrumInjector/FulcrumViewSupport/FulcrumDataConverters/HamburgerNavService.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumShim/res/fulcrum_shim.rc
Updated generator packages to include new logging changes and fixed some issues when building generators
=> Updated some packages for the generators 

FulcrumInjector/App.xaml.cs, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/packages.config
Updated view model setting routines to make them a little less complex
=> Updating develop to include newest changes for the view model refactors

FulcrumInjector/App.xaml.cs, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumModels/FulcrumVersionInfo.cs, FulcrumInjector/FulcrumViewContent/FulcrumModels/LogFileModels/FulcrumLogFileSet.cs, FulcrumInjector/FulcrumViewContent/FulcrumModels/WatchdogModels/WatchdogFile.cs, FulcrumInjector/FulcrumViewContent/FulcrumModels/WatchdogModels/WatchdogFolder.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/FulcrumSingletonContent.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/FulcrumViewModelBase.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumLogReviewViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumLogReviewView.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumInstaller/FulcrumShim.wxs
I Broke EVERYTHING. And Now it's unbroken. Built new packages and upgraded some references
=> Emergency PR into develop

.gitignore, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumShim/FulcrumShim.vcxproj, FulcrumShim/res/fulcrum_shim.rc
Upgraded some JSON conversion routines and included new Archive cleanup for child folders
=> Upgraded some JSON conversion routines

FulcrumInjector/AppSettings.json, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumLogReviewViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumSimulationPlaybackViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorOptionViewModels/FulcrumDebugLoggingViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorOptionViews/FulcrumDebugLoggingView.xaml.cs, FulcrumInjector/FulcrumViewSupport/FulcrumUpdater.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumInstaller/FulcrumShim.wxs, FulcrumShim/res/fulcrum_shim.rc
Updated some routines for sim generation and fixed some bugs with the creation of expressions files
=> Small simulation generation updates 

FulcrumInjector/AppSettings.json, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumModels/SettingsModels/FulcrumSettingsCollection.cs, FulcrumInjector/FulcrumViewContent/FulcrumModels/WatchdogModels/WatchdogFolder.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumSimulationPlaybackViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumShim/res/fulcrum_shim.rc
Simulation routine configuration is now built and fully functional. Need to do more field testing to complete changes and validate functionality totally, but it's good enough for the next release
=> Finished configuration routines for simulations

FulcrumInjector/AppSettings.json, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Updated some toggles and reworked the logic needed for logging locations
=> Quick hotfix for logging and logic for showing simulation configuration

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumMainWindow.xaml, FulcrumInjector/FulcrumViewContent/FulcrumModels/SettingsModels/FulcrumSettingEntryModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumModels/SettingsModels/FulcrumSettingsShare.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorOptionViewModels/FulcrumSettingsPaneViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumDllInjectionTestView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumInstalledOeAppsView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumPipeStatusView.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumJsonSupport/JsonConverters/SettingEntryJsonConverter.cs, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumDllInjectionTestViewStyles.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumInstalledOeAppsViewStyles.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumPipeStatusViewStyles.xaml, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumShim/res/fulcrum_shim.rc
Finally got around to making the UI Controls scale a little more nicely on the left sidebar. Main window content still doesn't fill the screen totally, but at least the text isn't warping anymore.
=> Updated Injector UI to scale

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/FulcrumInstalledOeAppsViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorCoreViewModels/FulcrumSimulationPlaybackViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumDllInjectionTestView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumInstalledOeAppsView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumInstalledOeAppsView.xaml.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumPipeStatusView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumSimulationPlaybackView.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumJsonSupport/JsonConverters/OeApplicationJsonConverter.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInjector/packages.config, FulcrumShim/res/fulcrum_shim.rc
Button for OE Apps was missing all functionality. Rebuilt logic for it and rebuilt view model logic as well. Behaves as expected again fortunately.
=> Fixed issues with the OE apps button

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Bootup screen added to contain the injector icon while the app is opening
=> Added booting splash screen

FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorCoreViews/FulcrumInstalledHardwareView.xaml, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Building and testing version changes
=> Build testing and publishing

FulcrumInjector/App.xaml.cs, FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumViewSupport/FulcrumCommandLine.cs, FulcrumInjector/FulcrumViewSupport/FulcrumControls/FulcrumEncryptionWindow.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumControls/FulcrumEncryptionWindow.xaml.cs, FulcrumInjector/FulcrumViewSupport/FulcrumServices/FulcrumDriveService.cs, FulcrumInjector/FulcrumViewSupport/FulcrumServices/FulcrumService.cs, FulcrumInjector/FulcrumViewSupport/FulcrumServices/FulcrumWatchdogService.cs, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Moved invoke routines into the CLI parse helper class
=> Refactored invoke routines

FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumDriveService/DriveServiceModels/DriveServiceSettings.cs, FulcrumServices/FulcrumDriveService/FulcrumDriveService.csproj, FulcrumServices/FulcrumDriveService/JsonConverters/DriveServiceSettingsJsonConverter.cs, FulcrumServices/FulcrumDriveService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumEmailService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumUpdaterService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumWatchdogService/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc
Drive service JSON conversion was failing due to issues with pulling encrypted values from the settings file. Fixed issues with those files and updated converters as needed.
=> Fixed issues with JSON conversions for DriveService

FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorMiscViewModels/FulcrumAboutThisAppViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorMiscViews/FulcrumAboutThisAppView.xaml, FulcrumInjector/FulcrumViewSupport/FulcrumModels/FulcrumVersionInfo.cs, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumAboutThisAppStyles.xaml, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumDriveService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumEmailService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumUpdaterService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumWatchdogService/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc, FulcrumSupport/FulcrumEncryption/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumJson/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumSupport/Properties/AssemblyInfo.cs
Updated version information for all components of the injector application
=> Completed version information updates

FulcrumInjector/FulcrumInjector.csproj, FulcrumInjector/FulcrumMainWindow.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViewModels/InjectorMiscViewModels/FulcrumEditOeAppViewModel.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumInstalledOeAppsView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/FulcrumInstalledOeAppsView.xaml.cs, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorMiscViews/FulcrumEditOeAppView.xaml, FulcrumInjector/FulcrumViewContent/FulcrumViews/InjectorMiscViews/FulcrumEditOeAppView.xaml.cs, FulcrumInjector/FulcrumViewSupport/FulcrumConstants.cs, FulcrumInjector/FulcrumViewSupport/FulcrumStyles/AppStyleSheets/FulcrumEditOeAppViewStyles.xaml, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumInstaller/FulcrumShim.wxs, FulcrumServices/FulcrumDriveService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumEmailService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumUpdaterService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumWatchdogService/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc, FulcrumSupport/FulcrumEncryption/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumJson/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumSupport/Properties/AssemblyInfo.cs
UI and backing logic for Editing OE apps in place. Merging into field testing branch for testing.
=> Merging OE app edit view into field testing

FulcrumInjector/AppSettings.json, FulcrumInjector/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumDriveService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumEmailService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumUpdaterService/Properties/AssemblyInfo.cs, FulcrumServices/FulcrumWatchdogService/Properties/AssemblyInfo.cs, FulcrumShim/res/fulcrum_shim.rc, FulcrumSupport/FulcrumEncryption/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumJson/JsonConfigFile.cs, FulcrumSupport/FulcrumJson/Properties/AssemblyInfo.cs, FulcrumSupport/FulcrumSupport/Properties/AssemblyInfo.cs
Moved to enum settings lookups for JSON loading.
=> Settings access updated to use enums instead of strings
